export const GET_ACTIVITY_OBJECT = 'GET_ACTIVITY_OBJECT';
export const GET_ACTIVITY_OF_TYPE = 'GET_ACTIVITY_OF_TYPE';
export const GET_ACTIVITY_OF_PRICE = 'GET_ACTIVITY_OF_PRICE';
export const GET_ACTIVITY_OF_PARTICIPANTS = 'GET_ACTIVITY_OF_PARTICIPANTS';

